/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class GetRestBootstrapRequest extends SpeakeasyBase {
  /**
   * can contain "single" and "all"
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=menu_with_images",
  })
  menuWithImages?: string;
}

export class GetRestBootstrapResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
