/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class GetRestCartRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=action",
  })
  action?: string;

  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=delete",
  })
  delete?: number;

  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=id_product",
  })
  idProduct?: number;

  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=id_product_attribute",
  })
  idProductAttribute?: number;

  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=image_size",
  })
  imageSize?: string;
}

export class GetRestCartResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
